<?php
 if (empty($section->parametrs->param0)) $section->parametrs->param0 = "30";
 if (empty($section->parametrs->param1)) $section->parametrs->param1 = "1";
 if (empty($section->parametrs->param2)) $section->parametrs->param2 = "125";
 if (empty($section->parametrs->param3)) $section->parametrs->param3 = "Добавить";
 if (empty($section->parametrs->param4)) $section->parametrs->param4 = "100";
 if (empty($section->parametrs->param5)) $section->parametrs->param5 = "300";
 if (empty($section->parametrs->param6)) $section->parametrs->param6 = "&nbsp;»&nbsp;";
 if (empty($section->parametrs->param7)) $section->parametrs->param7 = "Изменить";
 if (empty($section->parametrs->param8)) $section->parametrs->param8 = "Добавить комментарий:";
 if (empty($section->parametrs->param20)) $section->parametrs->param20 = "Добавить";
 if (empty($section->parametrs->param10)) $section->parametrs->param10 = "Вернуться назад";
 if (empty($section->parametrs->param11)) $section->parametrs->param11 = "дата:";
 if (empty($section->parametrs->param12)) $section->parametrs->param12 = "имя:";
 if (empty($section->parametrs->param14)) $section->parametrs->param14 = "Скачиваний:";
 if (empty($section->parametrs->param102)) $section->parametrs->param102 = "Просмотров:";
 if (empty($section->parametrs->param16)) $section->parametrs->param16 = "Добавить публикацию:";
 if (empty($section->parametrs->param17)) $section->parametrs->param17 = "Изменить публикацию:";
 if (empty($section->parametrs->param18)) $section->parametrs->param18 = "Имя:";
 if (empty($section->parametrs->param22)) $section->parametrs->param22 = "Название:";
 if (empty($section->parametrs->param23)) $section->parametrs->param23 = "Описание:";
 if (empty($section->parametrs->param24)) $section->parametrs->param24 = "Загрузить  рисунок:";
 if (empty($section->parametrs->param39)) $section->parametrs->param39 = "Загрузить скриншот";
 if (empty($section->parametrs->param44)) $section->parametrs->param44 = "Удалить картинку?";
 if (empty($section->parametrs->param25)) $section->parametrs->param25 = "Удалить публикацию?";
 if (empty($section->parametrs->param26)) $section->parametrs->param26 = "Добавить";
 if (empty($section->parametrs->param27)) $section->parametrs->param27 = "Сохранить";
 if (empty($section->parametrs->param28)) $section->parametrs->param28 = "365";
 if (empty($section->parametrs->param29)) $section->parametrs->param29 = "Не заполнено поле Имя";
 if (empty($section->parametrs->param32)) $section->parametrs->param32 = "Не заполнено поле Название";
 if (empty($section->parametrs->param33)) $section->parametrs->param33 = "Не заполнено поле Описание:";
 if (empty($section->parametrs->param34)) $section->parametrs->param34 = "Скачать";
 if (empty($section->parametrs->param38)) $section->parametrs->param38 = "2000";
 if (empty($section->parametrs->param40)) $section->parametrs->param40 = "800";
 if (empty($section->parametrs->param41)) $section->parametrs->param41 = "600";
 if (empty($section->parametrs->param42)) $section->parametrs->param42 = "20";
 if (empty($section->parametrs->param43)) $section->parametrs->param43 = "20";
 if (empty($section->parametrs->param45)) $section->parametrs->param45 = "url";
 if (empty($section->parametrs->param46)) $section->parametrs->param46 = "Имя ссылки:";
 if (empty($section->parametrs->param47)) $section->parametrs->param47 = "";
 if (empty($section->parametrs->param48)) $section->parametrs->param48 = "Удалить скриншот";
 if (empty($section->parametrs->param49)) $section->parametrs->param49 = "Ссылка";
 if (empty($section->parametrs->param50)) $section->parametrs->param50 = "Добавить скриншот";
 if (empty($section->parametrs->param51)) $section->parametrs->param51 = "Добавить ссылку";
 if (empty($section->parametrs->param52)) $section->parametrs->param52 = "Гость";
 if (empty($section->parametrs->param53)) $section->parametrs->param53 = "72";
 if (empty($section->parametrs->param54)) $section->parametrs->param54 = "72";
 if (empty($section->parametrs->param55)) $section->parametrs->param55 = "Сохранить";
 if (empty($section->parametrs->param56)) $section->parametrs->param56 = "Вернуться назад";
 if (empty($section->parametrs->param57)) $section->parametrs->param57 = "Описание";
 if (empty($section->parametrs->param58)) $section->parametrs->param58 = "Удалить комментарий";
 if (empty($section->parametrs->param59)) $section->parametrs->param59 = "Не верно введено число с картинки";
 if (empty($section->parametrs->param60)) $section->parametrs->param60 = "Не введено число с картинки";
 if (empty($section->parametrs->param61)) $section->parametrs->param61 = "Введите цифры с картинки";
 if (empty($section->parametrs->param63)) $section->parametrs->param63 = "Ужасно";
 if (empty($section->parametrs->param64)) $section->parametrs->param64 = "Плохо";
 if (empty($section->parametrs->param65)) $section->parametrs->param65 = "Средне";
 if (empty($section->parametrs->param66)) $section->parametrs->param66 = "Хорошо";
 if (empty($section->parametrs->param67)) $section->parametrs->param67 = "Отлично";
 if (empty($section->parametrs->param68)) $section->parametrs->param68 = "Голосовать";
 if (empty($section->parametrs->param69)) $section->parametrs->param69 = "Проголосовало";
 if (empty($section->parametrs->param70)) $section->parametrs->param70 = "чел.";
 if (empty($section->parametrs->param72)) $section->parametrs->param72 = "";
 if (empty($section->parametrs->param73)) $section->parametrs->param73 = "off";
 if (empty($section->parametrs->param92)) $section->parametrs->param92 = "255";
 if (empty($section->parametrs->param74)) $section->parametrs->param74 = "";
 if (empty($section->parametrs->param75)) $section->parametrs->param75 = "off";
 if (empty($section->parametrs->param93)) $section->parametrs->param93 = "255";
 if (empty($section->parametrs->param76)) $section->parametrs->param76 = "";
 if (empty($section->parametrs->param77)) $section->parametrs->param77 = "off";
 if (empty($section->parametrs->param94)) $section->parametrs->param94 = "255";
 if (empty($section->parametrs->param78)) $section->parametrs->param78 = "";
 if (empty($section->parametrs->param79)) $section->parametrs->param79 = "off";
 if (empty($section->parametrs->param95)) $section->parametrs->param95 = "255";
 if (empty($section->parametrs->param80)) $section->parametrs->param80 = "";
 if (empty($section->parametrs->param81)) $section->parametrs->param81 = "off";
 if (empty($section->parametrs->param96)) $section->parametrs->param96 = "255";
 if (empty($section->parametrs->param82)) $section->parametrs->param82 = "";
 if (empty($section->parametrs->param83)) $section->parametrs->param83 = "off";
 if (empty($section->parametrs->param97)) $section->parametrs->param97 = "255";
 if (empty($section->parametrs->param84)) $section->parametrs->param84 = "";
 if (empty($section->parametrs->param85)) $section->parametrs->param85 = "off";
 if (empty($section->parametrs->param98)) $section->parametrs->param98 = "255";
 if (empty($section->parametrs->param86)) $section->parametrs->param86 = "";
 if (empty($section->parametrs->param87)) $section->parametrs->param87 = "off";
 if (empty($section->parametrs->param99)) $section->parametrs->param99 = "255";
 if (empty($section->parametrs->param88)) $section->parametrs->param88 = "";
 if (empty($section->parametrs->param89)) $section->parametrs->param89 = "off";
 if (empty($section->parametrs->param100)) $section->parametrs->param100 = "255";
 if (empty($section->parametrs->param90)) $section->parametrs->param90 = "";
 if (empty($section->parametrs->param91)) $section->parametrs->param91 = "off";
 if (empty($section->parametrs->param101)) $section->parametrs->param101 = "255";
 if (empty($section->parametrs->param104)) $section->parametrs->param104 = "Искать на всех страницах";
 if (empty($section->parametrs->param105)) $section->parametrs->param105 = "Поиск";
 if (empty($section->parametrs->param106)) $section->parametrs->param106 = "Искать";
 if (empty($section->parametrs->param108)) $section->parametrs->param108 = "2";
   foreach($section->parametrs as $__paramitem){
    foreach($__paramitem as $__name=>$__value){
      if (empty($__value)){
      }
      if (preg_match("/\[%([\w\d\-]+)%\]/u", $__value, $m)!=false){
        $section->parametrs->$__name = $__data->prj->vars->$m[1];
      }
     }
   }
?>