<?php
 if (!isset($section->parametrs->param337) || $section->parametrs->param337=='') $section->parametrs->param337 = "n";
 if (!isset($section->parametrs->param50) || $section->parametrs->param50=='') $section->parametrs->param50 = "shopcart";
 if (!isset($section->parametrs->param331) || $section->parametrs->param331=='') $section->parametrs->param331 = "compare";
 if (!isset($section->parametrs->param273) || $section->parametrs->param273=='') $section->parametrs->param273 = "";
 if (!isset($section->parametrs->param60) || $section->parametrs->param60=='') $section->parametrs->param60 = "Y";
 if (!isset($section->parametrs->param15) || $section->parametrs->param15=='') $section->parametrs->param15 = "na";
 if (!isset($section->parametrs->param183) || $section->parametrs->param183=='') $section->parametrs->param183 = "Y";
 if (!isset($section->parametrs->param184) || $section->parametrs->param184=='') $section->parametrs->param184 = "v";
 if (!isset($section->parametrs->param207) || $section->parametrs->param207=='') $section->parametrs->param207 = "-1";
 if (!isset($section->parametrs->param243) || $section->parametrs->param243=='') $section->parametrs->param243 = "Y";
 if (!isset($section->parametrs->param276) || $section->parametrs->param276=='') $section->parametrs->param276 = "Y";
 if (!isset($section->parametrs->param113) || $section->parametrs->param113=='') $section->parametrs->param113 = "Y";
 if (!isset($section->parametrs->param237) || $section->parametrs->param237=='') $section->parametrs->param237 = "60";
 if (!isset($section->parametrs->param64) || $section->parametrs->param64=='') $section->parametrs->param64 = "24/36/60";
 if (!isset($section->parametrs->param235) || $section->parametrs->param235=='') $section->parametrs->param235 = "20";
 if (!isset($section->parametrs->param275) || $section->parametrs->param275=='') $section->parametrs->param275 = "Y";
 if (!isset($section->parametrs->param85) || $section->parametrs->param85=='') $section->parametrs->param85 = "N";
 if (!isset($section->parametrs->param266) || $section->parametrs->param266=='') $section->parametrs->param266 = "Y";
 if (!isset($section->parametrs->param292) || $section->parametrs->param292=='') $section->parametrs->param292 = "";
 if (!isset($section->parametrs->param325) || $section->parametrs->param325=='') $section->parametrs->param325 = "center";
 if (!isset($section->parametrs->param326) || $section->parametrs->param326=='') $section->parametrs->param326 = "70";
 if (!isset($section->parametrs->param310) || $section->parametrs->param310=='') $section->parametrs->param310 = "radio";
 if (!isset($section->parametrs->param318) || $section->parametrs->param318=='') $section->parametrs->param318 = "Y";
 if (!isset($section->parametrs->param323) || $section->parametrs->param323=='') $section->parametrs->param323 = "Y";
 if (!isset($section->parametrs->param269) || $section->parametrs->param269=='') $section->parametrs->param269 = "Y";
 if (!isset($section->parametrs->param327) || $section->parametrs->param327=='') $section->parametrs->param327 = "Y";
 if (!isset($section->parametrs->param295) || $section->parametrs->param295=='') $section->parametrs->param295 = "Y";
 if (!isset($section->parametrs->param233) || $section->parametrs->param233=='') $section->parametrs->param233 = "N";
 if (!isset($section->parametrs->param324) || $section->parametrs->param324=='') $section->parametrs->param324 = "Y";
 if (!isset($section->parametrs->param329) || $section->parametrs->param329=='') $section->parametrs->param329 = "Y";
 if (!isset($section->parametrs->param330) || $section->parametrs->param330=='') $section->parametrs->param330 = "";
 if (!isset($section->parametrs->param333) || $section->parametrs->param333=='') $section->parametrs->param333 = "Y";
 if (!isset($section->parametrs->param335) || $section->parametrs->param335=='') $section->parametrs->param335 = "0";
 if (!isset($section->parametrs->param336) || $section->parametrs->param336=='') $section->parametrs->param336 = "Y";
 if (!isset($section->parametrs->param339) || $section->parametrs->param339=='') $section->parametrs->param339 = "N";
 if (!isset($section->parametrs->param341) || $section->parametrs->param341=='') $section->parametrs->param341 = "Y";
 if (!isset($section->parametrs->param289) || $section->parametrs->param289=='') $section->parametrs->param289 = "350x350";
 if (!isset($section->parametrs->param114) || $section->parametrs->param114=='') $section->parametrs->param114 = "Y";
 if (!isset($section->parametrs->param83) || $section->parametrs->param83=='') $section->parametrs->param83 = "Y";
 if (!isset($section->parametrs->param84) || $section->parametrs->param84=='') $section->parametrs->param84 = "Y";
 if (!isset($section->parametrs->param111) || $section->parametrs->param111=='') $section->parametrs->param111 = "Y";
 if (!isset($section->parametrs->param226) || $section->parametrs->param226=='') $section->parametrs->param226 = "N";
 if (!isset($section->parametrs->param332) || $section->parametrs->param332=='') $section->parametrs->param332 = "Y";
 if (!isset($section->parametrs->param206) || $section->parametrs->param206=='') $section->parametrs->param206 = "316x0";
 if (!isset($section->parametrs->param57) || $section->parametrs->param57=='') $section->parametrs->param57 = "Y";
 if (!isset($section->parametrs->param73) || $section->parametrs->param73=='') $section->parametrs->param73 = "Y";
 if (!isset($section->parametrs->param74) || $section->parametrs->param74=='') $section->parametrs->param74 = "Y";
 if (!isset($section->parametrs->param65) || $section->parametrs->param65=='') $section->parametrs->param65 = "Y";
 if (!isset($section->parametrs->param55) || $section->parametrs->param55=='') $section->parametrs->param55 = "Y";
 if (!isset($section->parametrs->param205) || $section->parametrs->param205=='') $section->parametrs->param205 = "Y";
 if (!isset($section->parametrs->param297) || $section->parametrs->param297=='') $section->parametrs->param297 = "H1";
 if (!isset($section->parametrs->param344) || $section->parametrs->param344=='') $section->parametrs->param344 = "n";
 if (!isset($section->parametrs->param246) || $section->parametrs->param246=='') $section->parametrs->param246 = "Y";
 if (!isset($section->parametrs->param282) || $section->parametrs->param282=='') $section->parametrs->param282 = "Y";
 if (!isset($section->parametrs->param311) || $section->parametrs->param311=='') $section->parametrs->param311 = "N";
 if (!isset($section->parametrs->param293) || $section->parametrs->param293=='') $section->parametrs->param293 = "800x0";
 if (!isset($section->parametrs->param286) || $section->parametrs->param286=='') $section->parametrs->param286 = "440x440";
 if (!isset($section->parametrs->param285) || $section->parametrs->param285=='') $section->parametrs->param285 = "80x80";
 if (!isset($section->parametrs->param315) || $section->parametrs->param315=='') $section->parametrs->param315 = "150x150";
 if (!isset($section->parametrs->param320) || $section->parametrs->param320=='') $section->parametrs->param320 = "Y";
 if (!isset($section->parametrs->param319) || $section->parametrs->param319=='') $section->parametrs->param319 = "Y";
 if (!isset($section->parametrs->param313) || $section->parametrs->param313=='') $section->parametrs->param313 = "N";
 if (!isset($section->parametrs->param133) || $section->parametrs->param133=='') $section->parametrs->param133 = "Y";
 if (!isset($section->parametrs->param126) || $section->parametrs->param126=='') $section->parametrs->param126 = "Y";
 if (!isset($section->parametrs->param129) || $section->parametrs->param129=='') $section->parametrs->param129 = "Y";
 if (!isset($section->parametrs->param128) || $section->parametrs->param128=='') $section->parametrs->param128 = "Y";
 if (!isset($section->parametrs->param138) || $section->parametrs->param138=='') $section->parametrs->param138 = "Y";
 if (!isset($section->parametrs->param342) || $section->parametrs->param342=='') $section->parametrs->param342 = "N";
 if (!isset($section->parametrs->param343) || $section->parametrs->param343=='') $section->parametrs->param343 = "N";
 if (!isset($section->parametrs->param340) || $section->parametrs->param340=='') $section->parametrs->param340 = "N";
 if (!isset($section->parametrs->param312) || $section->parametrs->param312=='') $section->parametrs->param312 = "01";
 if (!isset($section->parametrs->param258) || $section->parametrs->param258=='') $section->parametrs->param258 = "Y";
 if (!isset($section->parametrs->param134) || $section->parametrs->param134=='') $section->parametrs->param134 = "Y";
 if (!isset($section->parametrs->param306) || $section->parametrs->param306=='') $section->parametrs->param306 = "Y";
 if (!isset($section->parametrs->param217) || $section->parametrs->param217=='') $section->parametrs->param217 = "Y";
 if (!isset($section->parametrs->param314) || $section->parametrs->param314=='') $section->parametrs->param314 = "Y";
 if (!isset($section->parametrs->param321) || $section->parametrs->param321=='') $section->parametrs->param321 = "5";
 if (!isset($section->parametrs->param322) || $section->parametrs->param322=='') $section->parametrs->param322 = "date";
 if (!isset($section->parametrs->param316) || $section->parametrs->param316=='') $section->parametrs->param316 = "Y";
 if (!isset($section->parametrs->param317) || $section->parametrs->param317=='') $section->parametrs->param317 = "Y";
 if (!isset($section->parametrs->param309) || $section->parametrs->param309=='') $section->parametrs->param309 = "h";
 if (!isset($section->parametrs->param307) || $section->parametrs->param307=='') $section->parametrs->param307 = "r";
 if (!isset($section->parametrs->param308) || $section->parametrs->param308=='') $section->parametrs->param308 = "c";
 if (!isset($section->parametrs->param305) || $section->parametrs->param305=='') $section->parametrs->param305 = "auto";
 if (!isset($section->parametrs->param303) || $section->parametrs->param303=='') $section->parametrs->param303 = "{name} - купить по цене {new price}: описание, характеристики, фото, отзывы";
 if (!isset($section->parametrs->param304) || $section->parametrs->param304=='') $section->parametrs->param304 = "Купить «{название товара} {производитель}» за {новая цена}[ со скидкой {скидка}%]. {описание товара}";
 if (!isset($section->parametrs->param328) || $section->parametrs->param328=='') $section->parametrs->param328 = "{features}";
 if (!isset($section->parametrs->param334) || $section->parametrs->param334=='') $section->parametrs->param334 = "N";
 if (!isset($section->parametrs->param350) || $section->parametrs->param350=='') $section->parametrs->param350 = "N";
 if (!isset($section->parametrs->param224) || $section->parametrs->param224=='') $section->parametrs->param224 = "optovik";
 if (!isset($section->parametrs->param225) || $section->parametrs->param225=='') $section->parametrs->param225 = "optcorp";
 if (!isset($section->parametrs->param346) || $section->parametrs->param346=='') $section->parametrs->param346 = "N";
 if (!isset($section->parametrs->param347) || $section->parametrs->param347=='') $section->parametrs->param347 = "Нажимая кнопку «Отправить», я принимаю условия <a href=\"/license/\" target=\"_blank\">Пользовательского соглашения</a> и даю своё согласие на обработку моих персональных данных";
 if (!isset($section->parametrs->param348) || $section->parametrs->param348=='') $section->parametrs->param348 = "N";
 if (!isset($section->parametrs->param349) || $section->parametrs->param349=='') $section->parametrs->param349 = "Принимаю <a href=\"#\" target=\"_blank\">условия</a>";
   foreach($section->parametrs as $__paramitem){
    foreach($__paramitem as $__name=>$__value){
      while (preg_match("/\[%([\w\d\-]+)%\]/u", $__value, $m)!=false){
        $__result = $__data->prj->vars->$m[1];
        $__value = str_replace($m[0], $__result, $__value);
      }
      $section->parametrs->$__name = $__value;
     }
   }
?>
